# Node.js with gulp
# Build a Node.js project using the gulp task runner.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: 'vs2017-win2016'

trigger:
  branches:
      include:
      - master

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    rm -rf node_modules
  displayName: 'Remove node_modules'

- script: |
    rm package-lock.json
  displayName: 'Remove package-lock.json'

- script: |
    npm install
  displayName: 'Run npm install'

- script: |
    npm test
  displayName: 'Run npm test'

- script: |
    gulp clean
    gulp bundle --ship
    gulp package-solution --ship
  displayName: 'Build and package the solution'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/drop'
    ArtifactName: 'drop'
    publishLocation: 'Container'

# Publish Test Results to Azure Pipelines
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit' # Options: JUnit, NUnit, VSTest, xUnit
    testResultsFiles: '**/summary-jest-junit.xml'
  displayName: 'Publish test results'